### ISSUE TITLE
 fluent-plugin-parser-cri    how  to  use  multiline

### ISSUE THREAD

**Issue by EasonHe** [fluent/fluent-plugin-parser-cri#5]
fluent-plugin-parser-cri    how  to  use  multiline

**Comment by kenhys** [comment]
I guess that the combination with fluent-plugin-concat is what you want to do.

ref. https://github.com/fluent-plugins-nursery/fluent-plugin-concat#usage

something like:

```
  <filter k8s>
    @type concat
    key message
    use_partial_cri_logtag true
    partial_cri_logtag_key logtag
    partial_cri_stream_key stream
  </filter>
```

**Comment by david-in-perth** [comment]
Note to self and future readers: Use an empty separator (`separator ""`) if you need messages to be concatenated without a line break (`\n`) between messages (Suggestion taken from https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/56). For example: when a JSON string has been split across multiple lines due to character limits, so line breaks will cause json parsing failures.

So the above example would become:
```
  <filter k8s>
    @type concat
    key message
    separator ""
    use_partial_cri_logtag true
    partial_cri_logtag_key logtag
    partial_cri_stream_key stream
  </filter>
```
